name: Linting

on: [push, pull_request]

env:
  CRATE_NAME: precious
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  lint:
    name: Check that code is lint clean using precious
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install mise
        run: |
          set -e
          set -x
          curl https://mise.run | sh
          mise install
      - name: Run precious
        run: |
          mise exec -- precious lint -a
